{
 "title": "Weather Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Altitude",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw611_altitude{job=\"haddock\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw611_pressure{job=\"haddock\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw611_temperature{scale=\"celcius\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (°F)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw611_temperature{scale=\"fahrenheit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Altitude evolution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "hw611_altitude{job=\"haddock\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pressure evolution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "expr": "hw611_pressure{job=\"haddock\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Temperature evolution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hw611_temperature{job=\"haddock\", scale=\"celcius\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (°F)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "hw611_temperature{job=\"haddock\", scale=\"fahrenheit\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}